### ISSUE TITLE
On logout the logo doesnt show

### ISSUE THREAD

**Issue by ardeay** [zesty-io/accounts-ui#126]
<img width="692" alt="Screen Shot 2020-03-27 at 7 15 32 PM" src="https://user-images.githubusercontent.com/729972/77812580-6e1fc000-705f-11ea-8576-94206ed9c0c2.png">
When my session dies, the logo doesnt load when i open the tab after timout

**Comment by d88naimi** [comment]
@ardeay I believe this has been resolved can this be closed?

<img width="1147" alt="Screen Shot 2021-03-31 at 1 18 43 PM" src="https://user-images.githubusercontent.com/22800749/113205908-a1bd9900-9223-11eb-91aa-88c9aa0c59cc.png">
