### ISSUE TITLE
Instance production link goes to wrong domain

### ISSUE THREAD

**Issue by shrunyan** [zesty-io/accounts-ui#132]
With the recent update to domain management allowing for multiple domains we need to update how the "Production Site" link is determine. This also affects `sites` repo which show live links to content.

# Issue
Currently we have instance which are using "dev" domains for the live site link.

![Screenshot from 2020-04-23 15-24-41](https://user-images.githubusercontent.com/208819/80155460-9de6b880-8576-11ea-8e44-b7fa0598b9ff.png)
_The "globe" icon links to the sites domain._

# Solution
Filter production link to only show those which point to a "live" branch.

**Comment by kakoga** [comment]
Randy asked me to add the following comments:
- Icon should reference new accounts domains endpoint and reference most recent entry
- currently references the instances object domain (which is now deprecated) in favor of new accounts endpoint - Hector can fix.
