### ISSUE TITLE
Create Instance Eco Dropdown Selecting None error

### ISSUE THREAD

**Issue by ardeay** [zesty-io/accounts-ui#148]
**Describe the bug**
When creating a new Instance if you click the Eco Dropdown and Selecting None you get a creation error because it tries to 0 as an arg. `invalid or unknown ZUID (0) provided for ecosystem`

![image](https://user-images.githubusercontent.com/729972/87733275-35c5fe00-c784-11ea-972d-db29239d69e2.png)

**To Reproduce**

1. login to accounts
2. Click on create instance
3.  click the Eco Dropdown and Select None
4. enter instance name
5. click create

**Expected behavior**
should not error and create an instance

**Comment by shrunyan** [comment]
fixed https://github.com/zesty-io/accounts-ui/commit/5d7326d457ba12f70cc2d69eb98914f9cf0c93fe
