### ISSUE TITLE
Poor experience for changing instance name 

### ISSUE THREAD

**Issue by kakoga** [zesty-io/accounts-ui#156]
**Describe the bug**
A customer recently asked if we could change the name of their instance. I explained that they could change it themselves by clicking on the name in the instance settings drawer, however there is no indication of it in the UI.

**To Reproduce**

1. Go to the Accounts UI and view the instance settings drawer
2. See that there is no visual indication that a user can change the instances name

**Expected behavior**
There should be some kind of visual clue that the user can click on the instance name in the setting drawer to change it.

**Screenshots**

<img width="1427" alt="Screen Shot 2020-10-06 at 2 00 34 PM" src="https://user-images.githubusercontent.com/16694502/95260447-968e3100-07dd-11eb-9db0-4c0e9a4ce2f1.png">

**Desktop (please complete the following information):**

- OS: Mac Catalina
- Browser Chrome
- Version 85.0.4183.121 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

n/a

**Additional context**

**Comment by shrunyan** [comment]
@d88naimi lets add an on hover display of the edit icon at the end of the name
