### ISSUE TITLE
Account-ui > Manage Account > Preference > Manage Teams

### ISSUE THREAD

**Issue by d88naimi** [zesty-io/accounts-ui#159]
**Describe the bug**
Toggle Manage Teams in My Account Preference section does not work.

**To Reproduce**
Accounts-ui > My Accounts > Preference section select Manage Teams toggle > will get a notification saying successful but it will not toggle over even on refresh. 

**Expected behavior**
Toggle to green should light up

**Screenshots**
<img width="733" alt="Screen Shot 2020-10-28 at 9 35 41 AM" src="https://user-images.githubusercontent.com/22800749/97467796-ca9ed280-1901-11eb-8bd4-28540ef083d7.png">

**Comment by d88naimi** [comment]
Update for ticket, the Manage Blueprints and Instance Grid View is not toggling as well.

**Comment by kakoga** [comment]
I've also had the blueprint toggle re-set itself too. I have logged in a few times and didn't have access to Blueprints until I went to  **my account** and flipped the toggle.

**Comment by shrunyan** [comment]
@d88naimi the blueprint toggle needs to be removed as the management of these has changed

**Comment by d88naimi** [comment]
@shrunyan looks like this one has been commented out https://github.com/zesty-io/accounts-ui/pull/161/files
Can this be closed?

**Comment by shrunyan** [comment]
@d88naimi is the original issue still relevant?
