### ISSUE TITLE
Instance card globe icon protocol always goes to https

### ISSUE THREAD

**Issue by kakoga** [zesty-io/accounts-ui#165]
**Describe the bug**
when clicking the live link from the instance card the link always sends the user to https. This causes sites to err out when they're not on https and confuses users.

**To Reproduce**

1. Go to an instance that you know is using http
2. Hover on the globe icon
3. See the link that is going to https
4. opt: click the globe icon to see the site err

**Expected behavior**
The globe icon should respect instance's protocol

**Screenshots**

<img width="460" alt="Screen Shot 2021-01-21 at 6 47 42 PM" src="https://user-images.githubusercontent.com/16694502/105530252-62f7e980-5c9c-11eb-9cac-ec2e54be7a8a.png">

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 87

**Comment by kakoga** [comment]
If the link is setup to always go to http any sites that are on https will automatically have their protocol upgraded.

**Comment by d88naimi** [comment]
@kakoga @shrunyan 

Like @kakoga mentioned the links are now automatically having ssl added to http to prevent malicious activity from happening. Im not sure what is best action to take on this ticket? Below are a couple suggestion but open to ideas.

One suggestion is to have a warning modal/ email letting the user know that their website isn't meeting security guidelines.

Another suggestion is on hover of the globe make the external link red with a small warning `https` is OFF

From accounts setting cog let the admin/user know that http is switched to off and provide link to manager-ui settings

**Comment by kakoga** [comment]
@d88naimi Hmm - @ardeay suggested making all http and the site will automatically upgrade if a site is using ssl & asked me to add it here. 
However, I think that if we want to enforce or recommend best practices regarding https then we should having a modal notifying the user _and_ give them direction on what do - in which case I'd need to write a doc or we need to find an mdn doc or similar to link to.

I think that the little red warning is fine too but to avoid alarming using I think a more verbose modal would be the way to go :)
