### ISSUE TITLE
Accounts UI not loading unless on incognito mode

### ISSUE THREAD

**Issue by giseleblair** [zesty-io/accounts-ui#166]
**Describe the bug**
Users are reporting the Accounts UI not loading and getting stuck with the message "Finding Your Account"

**To Reproduce**

1. Go to accounts.zesty.io
2. See that the UI is stuck without loading instances or login screen.

**Expected behavior**
Expect a instances to load or login module to display when loading accounts.zesty.io

**Screenshots**

Sensitive client information. Zesty staff access only. See internal note in Zendesk for screen capture: https://zestysupport.zendesk.com/agent/tickets/1121

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Additional context**
I have not been able to recreate this on my end but have multiple reports from client about the occurrence. See internal note on Zendesk for screen capture.

**Comment by shrunyan** [comment]
@giseleblair I assume this is not an on going issue. Can this be closed?
