### ISSUE TITLE
Inside instance settings under Set Your Domain -- the add domain button is unavailable when domain is formatted correctly 

### ISSUE THREAD

**Issue by bltarkany** [zesty-io/accounts-ui#213]
**Describe the bug**
Inside instance settings drawer under Set Your Domain of the publish your instance box -- the add domain button is unavailable when domain is formatted correctly. However when the domain to be added is formatted incorrectly and includes protocols the add domain button becomes available.

**Expected behavior**
without protocols the button should be available.

**Screenshots**
Testing Video:
[https://www.loom.com/share/36d1678c78df4fae82954ab4f4eb1ba5](https://www.loom.com/share/36d1678c78df4fae82954ab4f4eb1ba5)

**Comment by d88naimi** [comment]
Spoke with @bltarkany  and we couldn't replicate this one so I'm closing.
