### ISSUE TITLE
Accounts - Profile name change

### ISSUE THREAD

**Issue by Katiemoser** [zesty-io/accounts-ui#232]
change works but the content in the edit field reverts back to the original content after save. The label and overall name update, however the interior text does not update to the new value.

**Comment by Katiemoser** [comment]
- change works but the content in the edit field reverts back to the original content after save. The label and overall name update, however the interior text does not update to the new value.

**Comment by giseleblair** [comment]
Closing from this repo. Recreated here: https://github.com/zesty-io/website/issues/1167

**Comment by giseleblair** [comment]
Closing from this repo. Recreated here: https://github.com/zesty-io/website/issues/1167
